import type { CustomerCredentialRecord, CustomerRecord } from "./types";

export const SEED_CUSTOMERS: CustomerRecord[] = [
  {
    id: "741",
    code: "CR00079HN",
    name: "FERAHIM",
    lastName: "HESENOV",
    group: "NEFTCILER",
    canUseCurrency: 0,
    currencyCode: "USD",
    priceClass: 1,
    debtAgingGroup: 1,
    isRiskyCustomer: 0,
    birthDate: null,
    isActive: 1,
    department: "NEFTCILER",
    phone: "+994 55 375 85 00",
    mobilePhone: null,
    phoneNormalized: "994553758500",
    mobileNormalized: null,
  },
  {
    id: "747",
    code: "CR00156HE",
    name: "AGDERELI",
    lastName: "NIGAR",
    group: "EHMEDLI",
    canUseCurrency: 0,
    currencyCode: "USD",
    priceClass: 1,
    debtAgingGroup: 1,
    isRiskyCustomer: 0,
    birthDate: null,
    isActive: 1,
    department: "EHMEDLI",
    phone: "0513053922",
    mobilePhone: null,
    phoneNormalized: "994513053922",
    mobileNormalized: null,
  },
  {
    id: "756",
    code: "CR00009XS",
    name: "ELI ",
    lastName: "HUSEYNOV",
    group: "SUMQAYIT",
    canUseCurrency: 0,
    currencyCode: "USD",
    priceClass: 1,
    debtAgingGroup: 1,
    isRiskyCustomer: 0,
    birthDate: null,
    isActive: 1,
    department: "SXATUN",
    phone: "0703331135",
    mobilePhone: "070 333 11 35",
    phoneNormalized: "994703331135",
    mobileNormalized: "994703331135",
  },
  {
    id: "783",
    code: "CR00017x",
    name: "ILAHE",
    lastName: "HUSEYINOVA",
    group: "GENCE",
    canUseCurrency: 1,
    currencyCode: "USD",
    priceClass: 1,
    debtAgingGroup: 1,
    isRiskyCustomer: 0,
    birthDate: null,
    isActive: 1,
    department: "XATUN1",
    phone: null,
    mobilePhone: "0554195753",
    phoneNormalized: null,
    mobileNormalized: "994554195753",
  },
];

export const DEMO_PASSWORD = "123456";
export const DEMO_OTP = "123456";

export const SEED_CUSTOMER_CREDENTIALS: CustomerCredentialRecord[] = SEED_CUSTOMERS.map(
  (customer) => ({
    customerId: customer.id,
    password: DEMO_PASSWORD,
  }),
);
